// Code generated by goctl. DO NOT EDIT.
package types

type Position struct {
	XStart uint32 `json:"xStart,range=[0:10000]"` // 取值范围0-10000 。 以左上为原点，元素百分比坐标，比如元素在x轴的92.5%，取值为9250
	YStart uint32 `json:"yStart,range=[0:10000]"`
	XEnd   uint32 `json:"xEnd,range=[0:10000]"`
	YEnd   uint32 `json:"yEnd,range=[0:10000]"`
}

type AddElementRequest struct {
	AppId         string   `json:"appId,options=xhb|dyt"`                // 哪个应用
	Platform      string   `json:"platform,options=android|iOS|flutter"` // 平台
	Version       string   `json:"version"`                              // app 版本
	ComponentName string   `json:"componentName"`
	Path          string   `json:"path,optional"`
	Name          string   `json:"name,optional"`
	Picture       string   `json:"picture"`              // 元素截图的 base64 编码 ，如果是页面则是页面截图
	FullPicture   string   `json:"fullPicture,optional"` // 元素所属页面的截图  ，如果是页面，该字段为空
	Position      Position `json:"position,optional"`
	IsPage        bool     `json:"isPage"`
	PageTitle     string   `json:"pageTitle"`                         // 页面的 title
	IsOverride    bool     `json:"isOverride,optional,default=false"` // 是否覆盖记录
}

type AppQueryListRequest struct {
	AppId    string `json:"appId,options=xhb|dyt"`                // 哪个应用
	Platform string `json:"platform,options=android|iOS|flutter"` // 平台
	Version  string `json:"version"`                              // app 版本
}

type AppQueryResponseItem struct {
	IsPage        bool      `json:"isPage"`
	ComponentName string    `json:"componentName"`
	Path          string    `json:"path,omitempty"`
	Position      *Position `json:"position,omitempty"`
	Name          string    `json:"name"` // 用户填写的埋点名称
}

type AppQueryListResponse struct {
	Items []*AppQueryResponseItem `json:"items"`
}

type AddModuleRequest struct {
	ModuleName string `json:"moduleName"`
}

type DeleteModuleRequest struct {
	Id int64 `json:"id"`
}

type QueryModuleListRequest struct {
	ModuleName string `json:"moduleName,optional"`
}

type QueryModuleListResponse struct {
	ModuleList []*Module `json:"moduleList"`
}

type Module struct {
	Id         int64  `json:"id"`
	ModuleName string `json:"moduleName"`
}

type WebQueryPageRequest struct {
	ModuleId    int    `json:"moduleId,optional"`
	SearchStr   string `json:"searchStr,optional"`
	CurrentPage int    `json:"currentPage"`
	PageSize    int    `json:"pageSize,optional,default=15"`
}

type WebQueryPageItem struct {
	Platform       string `json:"platform"`
	PageUrl        string `json:"pageUrl"`
	PageName       string `json:"pageName"`
	PageModuleName string `json:"pageModuleName"`
	PageId         string `json:"pageId"`
	PageGroupId    string `json:"pageGroupId"`
}

type WebQueryPageResponse struct {
	Pages []*WebQueryPageItem `json:"pages"`
}

type UpdateElementRequest struct {
	Id        int     `json:"id"`
	TraceName *string `json:"traceName,optional"`
}

type UpdatePageNameRequest struct {
	PageGroupId string `json:"pageGroupId"`
	PageName    string `json:"pageName"`
}

type UpdatePageModuleIdRequest struct {
	PageGroupId  string `json:"pageGroupId"`
	PageModuleId int    `json:"pageModuleId,optional,range=[1:]"` // 0是全部 ，-1是未分类
}

type UpdatePageOrderRequest struct {
	ModuleId     int      `json:"moduleId"`
	PageGroupIds []string `json:"pageGroupIds"`
}

type QueryPageDetailRequest struct {
	PageGroupId string `json:"pageGroupId"`
}

type QueryPageDetailResponse struct {
	AndroidElements map[string]*ElementTree   `json:"androidElements"` // map的key 是 version
	AndroidId       int                       `json:"androidId"`
	AndroidPageInfo map[string]*PageTraceInfo `json:"androidPageInfo"`
	IOSElements     map[string]*ElementTree   `json:"iosElements"`
	IOSId           int                       `json:"iosId"`
	IOSPageInfo     map[string]*PageTraceInfo `json:"iosPageInfo"`
}

type PageTraceInfo struct {
	PageId        string `json:"pageId"`
	PageName      string `json:"pageName"`
	ComponentName string `json:"componentName"`
	Id            int64  `json:"id"`
	Picture       string `json:"picture"`
}

type ElementTree struct {
	TraceName     string         `json:"traceName"`
	TraceType     string         `json:"traceType"`
	ComponentName string         `json:"componentName"`
	Path          string         `json:"path"` // 和componentName 拼在一起就是埋点的全路经
	SubPath       string         `json:"subPath"`
	Id            int            `json:"id"`          // 埋点的主键 id
	Picture       string         `json:"picture"`     // 元素的截图
	FullPicture   string         `json:"fullPicture"` // 元素所在页面的截图
	Position      *Position      `json:"position"`    // 位置信息
	Children      []*ElementTree `json:"children"`
}

type QueryRelatedPageRequest struct {
	Id          int `json:"id"`
	CurrentPage int `json:"currentPage"`
	PageSize    int `json:"pageSize,optional,default=15"`
}

type QueryRelatedPageResponse struct {
	Pages []*WebQueryPageItem `json:"pages"`
}

type RelatedPageItem struct {
	Picture string `json:"picture"`
	Id      int    `json:"id"`
}

type UpdateModuleRequest struct {
	ModuleId   int    `json:"moduleId"`
	ModuleName string `json:"moduleName"`
}

type QueryHasDataRequest struct {
	Id int `json:"id"`
}

type QueryHasDataResponse struct {
	Has bool `json:"has"`
}

type QuerySevenDataRequest struct {
	Id int `json:"id"`
}

type QueryOneDataRequest struct {
	Id int `json:"id"`
}

type QueryOneDataResponse struct {
	Data map[string]interface{} `json:"data"`
}

type QuerySevenDataResponse struct {
	Data map[int64]int64 `json:"data"`
}

type MovePageMatchRequest struct {
	PageGroupId string `json:"pageGroupId"`
	Platform    string `json:"platform"`
}

type MovePageMatchResponse struct {
	NewPageGroupId string `json:"newPageGroupId"`
}

type DeletePageRequest struct {
	PageId   string `json:"pageId"`
	Platform string `json:"platform"`
	Version  string `json:"version"`
}

type DeleteTraceRequest struct {
	ComponentName string `json:"componentName"`
	Path          string `json:"path"`
	Version       string `json:"version"`
	Platform      string `json:"platform"`
	IsAllVersion  bool   `json:"isAllVersion"` // 是否删除所有的版本，如果该字段true，version 的值无效
}

type ElementGroup struct {
	ComponentName      string `json:"componentName"`
	Platform           string `json:"platform,options=android|iOS|flutter"` // 平台
	TraceType          int64  `json:"traceType"`
	CurrentElementPath string `json:"currentElementPath"`
	CurrentAppVersion  string `json:"currentAppVersion"`
	OldElementPath     string `json:"oldElementPath"`
	OldAppVersion      string `json:"oldAppVersion"`
}

type ElementItem struct {
	ComponentName     string `json:"componentName"`
	Platform          string `json:"platform,options=android|iOS|flutter"` // 平台
	TraceType         int64  `json:"traceType"`
	CurrentAppVersion string `json:"currentAppVersion"`
	ElementPath       string `json:"elementPath"`
}

type TraceGroupInsertRequest struct {
	ElementChange    []ElementGroup `json:"elementChange,optional"`
	ElementNew       []ElementItem  `json:"elementNew,optional"`
	ElementUnchanged []ElementItem  `json:"elementUnchanged"`
}

type QueryTraceGroupRequest struct {
	Id int `json:"id"`
}

type QueryTraceGroupResoponse struct {
	GroupId string            `json:"groupId"`
	Groups  map[string]string `json:"groups"` // key是版本号，value是路径
}
