stages:
  - lint
  - build
  - deploy

buildTest_job:
  stage: build
  image: node:14
  tags:
    - frontend
  artifacts:
    name: '${CI_JOB_NAME}_${CI_COMMIT_REF_NAME}_dist'
    expire_in: 1 week
    paths:
      - dist.tar.gz
  only:
    - dev
    - test
  script:
    - make build

build_job:
  stage: build
  image: node:14
  tags:
    - frontend-pre
  artifacts:
    name: '${CI_JOB_NAME}_${CI_COMMIT_REF_NAME}_dist'
    expire_in: 1 week
    paths:
      - dist.tar.gz
  only:
    - pre
    - master
  script:
    - make build
